# Generated by Django 3.0.6 on 2020-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie1', models.CharField(max_length=40)),
                ('rating1', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('movie2', models.CharField(blank=True, max_length=40, null=True)),
                ('rating2', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('movie3', models.CharField(blank=True, max_length=40, null=True)),
                ('rating3', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('movie4', models.CharField(blank=True, max_length=40, null=True)),
                ('rating4', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('movie5', models.CharField(blank=True, max_length=40, null=True)),
                ('rating5', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
            ],
        ),
    ]
