# Generated by Django 3.0.6 on 2020-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0002_movies_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='phone_no',
            field=models.IntegerField(default=None),
        ),
    ]
